In [ ]:
# numpy 

In [2]:
import numpy as np

In [5]:
# np.arange(a)  = a 직전까지

# reshape(행-가로, 열-세로)

a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
# linspace = 1 ~ 10 까지 8 조각 내라 

a = np.linspace(1,10,8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [7]:
a = np.array(['1.55', '0.23', '5.21', '5'])
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.dtype)
#U4 = int32 (32bit 정수형)

<U4


In [12]:
# type 바꾸기

a = a.astype(float)
print(a.dtype)

float64


In [13]:
a = np.array([1,2,3,4,5])

[4 5]


In [15]:
# 3보다 큰 값만 

print(a[a>3])

[4 5]


In [17]:
# 짝수만

# % modular 연산자 = 나머지 
print(a[(a%2) == 0])

[2 4]


In [18]:
# slicing 

print(a[1:3])

[2 3]


In [19]:
# 처음부터 ~ 3까지
print(a[:3])

[1 2 3]


In [20]:
# 2차원 배열

#10~100 전까지 10조각 -> 3 행 3 열
a = np.arange(10, 100, 10).reshape(3,3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [21]:

# slicing

print(a[1:3, 1:3])

[[50 60]
 [80 90]]


In [5]:
# np.sum 

arr = np.array([1,2,3,4,5])
arr.sum()


15

In [ ]:
# sum(axis=0)     axis 어떤 축을 기준으로 연산할 것인가 지정.

# (3, 4)의 shape인 행렬을

# axis=0으로 지정하면 row(가로)를 기준으로 연산
# axis=1으로 지정하면 column(세로)을 기준으로 연산